#!/bin/sh
#
# @(#)RunCldc	1.9	06/10/10
#
# Copyright  1990-2008 Sun Microsystems, Inc. All Rights Reserved.
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License version
# 2 only, as published by the Free Software Foundation. 
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License version 2 for more details (a copy is
# included at /legal/license.txt). 
# 
# You should have received a copy of the GNU General Public License
# version 2 along with this work; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
# 02110-1301 USA 
# 
# Please contact Sun Microsystems, Inc., 4150 Network Circle, Santa
# Clara, CA 95054 or visit www.sun.com if you need additional
# information or have any questions. 
#

#
# CLDCmain has a parameter list of this form:
# -impl <path> -classpath <path> <classname> <classargs>
# The implementation and midlet paths are :-separated lists
# of JAR files. By default, CLDCmain doesn't require any implementation
# so the empty file is used below.
# The order of the implementation and midlet paths is unimportant,
# but once the classname parameter is seen, parsing stops and all
# the following parameters are passed to that class's main method.
#
# The script or user that invokes this script is thus expected to write:
#
# RunCldc -midlet <your test JAR file> <classname> <classargs>
 
Homedir=`dirname $0`
. ${Homedir}/SetCvmHome

CvmDualStack=${CvmRoot}/src/share/javavm/test/dualstack

Cvm=${CvmHome}/bin/cvm

${Cvm} -classpath ${CvmDualStack}/app.jar \
	-Djava.security.policy=${CvmDualStack}/AMSPolicyFile \
	com.sun.javax.microedition.CLDCmain \
	-impl ${CvmDualStack}/empty \
	$*
