/*
 * @(#)cvm_jni_funcs.i	1.4 06/10/04
 *
 * Copyright  1990-2008 Sun Microsystems, Inc. All Rights Reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License version
 * 2 only, as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License version 2 for more details (a copy is
 * included at /legal/license.txt).
 *
 * You should have received a copy of the GNU General Public License
 * version 2 along with this work; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA
 *
 * Please contact Sun Microsystems, Inc., 4150 Network Circle, Santa
 * Clara, CA 95054 or visit www.sun.com if you need additional
 * information or have any questions.
 */

ENTRY0(ansiJavaMain0) ENTRY_SEP
ENTRY(Java_java_lang_reflect_Array_getBoolean) ENTRY_SEP
ENTRY(Java_java_lang_reflect_Array_getByte) ENTRY_SEP
ENTRY(Java_java_lang_reflect_Array_getChar) ENTRY_SEP
ENTRY(Java_java_lang_reflect_Array_getDouble) ENTRY_SEP
ENTRY(Java_java_lang_reflect_Array_getFloat) ENTRY_SEP
ENTRY(Java_java_lang_reflect_Array_getInt) ENTRY_SEP
ENTRY(Java_java_lang_reflect_Array_getLength) ENTRY_SEP
ENTRY(Java_java_lang_reflect_Array_getLong) ENTRY_SEP
ENTRY(Java_java_lang_reflect_Array_getShort) ENTRY_SEP
ENTRY(Java_java_lang_reflect_Array_multiNewArray) ENTRY_SEP
ENTRY(Java_java_lang_reflect_Array_newArray) ENTRY_SEP
ENTRY(Java_java_lang_reflect_Array_setBoolean) ENTRY_SEP
ENTRY(Java_java_lang_reflect_Array_setByte) ENTRY_SEP
ENTRY(Java_java_lang_reflect_Array_setChar) ENTRY_SEP
ENTRY(Java_java_lang_reflect_Array_setDouble) ENTRY_SEP
ENTRY(Java_java_lang_reflect_Array_setFloat) ENTRY_SEP
ENTRY(Java_java_lang_reflect_Array_setInt) ENTRY_SEP
ENTRY(Java_java_lang_reflect_Array_setLong) ENTRY_SEP
ENTRY(Java_java_lang_reflect_Array_setShort) ENTRY_SEP
ENTRY(Java_java_lang_CharacterData_setArrays) ENTRY_SEP
ENTRY(Java_java_lang_CharacterDataLatin1_setArrays) ENTRY_SEP
ENTRY(Java_java_lang_Class_addToLoaderCache) ENTRY_SEP
ENTRY(Java_java_lang_Class_checkErrorFlag) ENTRY_SEP
ENTRY(Java_java_lang_Class_checkInitializedFlag) ENTRY_SEP
ENTRY(Java_java_lang_Class_checkInitializingFlag) ENTRY_SEP
ENTRY(Java_java_lang_Class_clearInitializingFlag) ENTRY_SEP
ENTRY(Java_java_lang_Class_clearSuperClassesLoadedFlag) ENTRY_SEP
ENTRY(Java_java_lang_Class_forName0) ENTRY_SEP
ENTRY(Java_java_lang_Class_getClassTypeID) ENTRY_SEP
ENTRY(Java_java_lang_Class_getInterfaceName) ENTRY_SEP
ENTRY(Java_java_lang_Class_getInterfaceTypeID) ENTRY_SEP
ENTRY(Java_java_lang_Class_getNumInterfaces) ENTRY_SEP
ENTRY(Java_java_lang_Class_getPrimitiveClass) ENTRY_SEP
ENTRY(Java_java_lang_Class_getSuperClassName) ENTRY_SEP
ENTRY(Java_java_lang_Class_getSuperClassTypeID) ENTRY_SEP
ENTRY(Java_java_lang_Class_isAssignableFrom) ENTRY_SEP
ENTRY(Java_java_lang_Class_isInstance) ENTRY_SEP
ENTRY(Java_java_lang_Class_linkSuperClasses) ENTRY_SEP
ENTRY(Java_java_lang_Class_notifyClassLoaded) ENTRY_SEP
ENTRY(Java_java_lang_Class_setErrorFlag) ENTRY_SEP
ENTRY(Java_java_lang_Class_setInitializedFlag) ENTRY_SEP
ENTRY(Java_java_lang_Class_setInitializingFlag) ENTRY_SEP
ENTRY(Java_java_lang_Class_superClassesLoaded) ENTRY_SEP
ENTRY(Java_java_lang_ClassLoader_00024NativeLibrary_find) ENTRY_SEP
ENTRY(Java_java_lang_ClassLoader_00024NativeLibrary_initIDs) ENTRY_SEP
ENTRY(Java_java_lang_ClassLoader_00024NativeLibrary_load) ENTRY_SEP
ENTRY(Java_java_lang_ClassLoader_00024NativeLibrary_unload) ENTRY_SEP
ENTRY(Java_java_lang_ClassLoader_InitializeLoaderGlobalRoot) ENTRY_SEP
ENTRY(Java_java_lang_ClassLoader_defineClass0) ENTRY_SEP
ENTRY(Java_java_lang_ClassLoader_findLoadedClass0) ENTRY_SEP
ENTRY(Java_java_lang_ClassLoader_getCallerClassLoader) ENTRY_SEP
ENTRY(Java_java_lang_ClassLoader_loadBootstrapClass0) ENTRY_SEP
ENTRY(Java_java_lang_ClassLoader_resolveClass0) ENTRY_SEP
ENTRY(Java_java_net_DatagramPacket_init) ENTRY_SEP
ENTRY(Java_java_lang_Double_doubleToLongBits) ENTRY_SEP
ENTRY(Java_java_lang_Double_doubleToRawLongBits) ENTRY_SEP
ENTRY(Java_java_lang_Double_longBitsToDouble) ENTRY_SEP
ENTRY(Java_java_io_FileDescriptor_initIDs) ENTRY_SEP
ENTRY(Java_java_io_FileDescriptor_sync) ENTRY_SEP
ENTRY(Java_java_io_FileInputStream_available) ENTRY_SEP
ENTRY(Java_java_io_FileInputStream_close0) ENTRY_SEP
ENTRY(Java_java_io_FileInputStream_initIDs) ENTRY_SEP
ENTRY(Java_java_io_FileInputStream_open) ENTRY_SEP
ENTRY(Java_java_io_FileInputStream_readBytes) ENTRY_SEP
ENTRY(Java_java_io_FileInputStream_skip) ENTRY_SEP
ENTRY(Java_java_io_FileOutputStream_close0) ENTRY_SEP
ENTRY(Java_java_io_FileOutputStream_initIDs) ENTRY_SEP
ENTRY(Java_java_io_FileOutputStream_openAppend) ENTRY_SEP
ENTRY(Java_java_io_FileOutputStream_writeBytes) ENTRY_SEP
ENTRY(Java_java_io_FileSystem_getFileSystem) ENTRY_SEP
ENTRY(Java_java_lang_ref_Finalizer_invokeFinalizeMethod) ENTRY_SEP
ENTRY(Java_java_lang_Float_floatToIntBits) ENTRY_SEP
ENTRY(Java_java_lang_Float_floatToRawIntBits) ENTRY_SEP
ENTRY(Java_java_lang_Float_intBitsToFloat) ENTRY_SEP
ENTRY(Java_sun_misc_GC_maxObjectInspectionAge) ENTRY_SEP
ENTRY(Java_java_net_Inet4Address_init) ENTRY_SEP
ENTRY(Java_java_net_Inet4AddressImpl_getHostByAddr) ENTRY_SEP
ENTRY(Java_java_net_Inet4AddressImpl_getLocalHostName) ENTRY_SEP
ENTRY(Java_java_net_Inet4AddressImpl_lookupAllHostAddr) ENTRY_SEP
ENTRY(Java_java_net_Inet6Address_init) ENTRY_SEP
ENTRY(Java_java_net_Inet6AddressImpl_getHostByAddr) ENTRY_SEP
ENTRY(Java_java_net_Inet6AddressImpl_getLocalHostName) ENTRY_SEP
ENTRY(Java_java_net_Inet6AddressImpl_lookupAllHostAddr) ENTRY_SEP
ENTRY(Java_java_net_InetAddress_init) ENTRY_SEP
ENTRY(Java_java_net_InetAddressImplFactory_isIPv6Supported) ENTRY_SEP
ENTRY(Java_java_util_zip_Inflater_end) ENTRY_SEP
ENTRY(Java_java_util_zip_Inflater_getAdler) ENTRY_SEP
ENTRY(Java_java_util_zip_Inflater_getTotalIn) ENTRY_SEP
ENTRY(Java_java_util_zip_Inflater_getTotalOut) ENTRY_SEP
ENTRY(Java_java_util_zip_Inflater_inflateBytes) ENTRY_SEP
ENTRY(Java_java_util_zip_Inflater_initIDs) ENTRY_SEP
ENTRY(Java_java_util_zip_Inflater_reset) ENTRY_SEP
ENTRY(Java_java_util_zip_Inflater_setDictionary) ENTRY_SEP
ENTRY(Java_sun_misc_JIT_compileMethod) ENTRY_SEP
ENTRY(Java_sun_misc_JIT_neverCompileMethod) ENTRY_SEP
ENTRY(Java_sun_misc_Launcher_00024AppClassLoader_findContainer) ENTRY_SEP
ENTRY(Java_java_net_NetworkInterface_getAll) ENTRY_SEP
ENTRY(Java_java_net_NetworkInterface_getByIndex) ENTRY_SEP
ENTRY(Java_java_net_NetworkInterface_getByInetAddress0) ENTRY_SEP
ENTRY(Java_java_net_NetworkInterface_getByName0) ENTRY_SEP
ENTRY(Java_java_net_NetworkInterface_init) ENTRY_SEP
ENTRY(Java_java_lang_Object_getClass) ENTRY_SEP
ENTRY(Java_java_io_ObjectInputStream_allocateNewArray) ENTRY_SEP
ENTRY(Java_java_io_ObjectInputStream_allocateNewObject) ENTRY_SEP
ENTRY(Java_java_io_ObjectInputStream_bytesToDoubles) ENTRY_SEP
ENTRY(Java_java_io_ObjectInputStream_bytesToFloats) ENTRY_SEP
ENTRY(Java_java_io_ObjectInputStream_latestUserDefinedLoader) ENTRY_SEP
ENTRY(Java_java_io_ObjectInputStream_setObjectFieldValue) ENTRY_SEP
ENTRY(Java_java_io_ObjectInputStream_setPrimitiveFieldValues) ENTRY_SEP
ENTRY(Java_java_io_ObjectOutputStream_doublesToBytes) ENTRY_SEP
ENTRY(Java_java_io_ObjectOutputStream_floatsToBytes) ENTRY_SEP
ENTRY(Java_java_io_ObjectOutputStream_getObjectFieldValue) ENTRY_SEP
ENTRY(Java_java_io_ObjectOutputStream_getPrimitiveFieldValues) ENTRY_SEP
ENTRY(Java_java_io_ObjectStreamClass_getFieldIDs) ENTRY_SEP
ENTRY(Java_java_io_ObjectStreamClass_hasStaticInitializer) ENTRY_SEP
ENTRY(Java_java_io_ObjectStreamClass_initNative) ENTRY_SEP
ENTRY(Java_java_lang_Package_getSystemPackage0) ENTRY_SEP
ENTRY(Java_java_lang_Package_getSystemPackages0) ENTRY_SEP
ENTRY(Java_java_net_PlainDatagramSocketImpl_bind) ENTRY_SEP
ENTRY(Java_java_net_PlainDatagramSocketImpl_connect0) ENTRY_SEP
ENTRY(Java_java_net_PlainDatagramSocketImpl_datagramSocketClose) ENTRY_SEP
ENTRY(Java_java_net_PlainDatagramSocketImpl_datagramSocketCreate) ENTRY_SEP
ENTRY(Java_java_net_PlainDatagramSocketImpl_disconnect0) ENTRY_SEP
ENTRY(Java_java_net_PlainDatagramSocketImpl_getTimeToLive) ENTRY_SEP
ENTRY(Java_java_net_PlainDatagramSocketImpl_init) ENTRY_SEP
ENTRY(Java_java_net_PlainDatagramSocketImpl_join) ENTRY_SEP
ENTRY(Java_java_net_PlainDatagramSocketImpl_leave) ENTRY_SEP
ENTRY(Java_java_net_PlainDatagramSocketImpl_peekData) ENTRY_SEP
ENTRY(Java_java_net_PlainDatagramSocketImpl_receive) ENTRY_SEP
ENTRY(Java_java_net_PlainDatagramSocketImpl_send) ENTRY_SEP
ENTRY(Java_java_net_PlainDatagramSocketImpl_setTimeToLive) ENTRY_SEP
ENTRY(Java_java_net_PlainDatagramSocketImpl_socketGetOption) ENTRY_SEP
ENTRY(Java_java_net_PlainDatagramSocketImpl_socketSetOption) ENTRY_SEP
ENTRY(Java_java_lang_reflect_Proxy_defineClass0) ENTRY_SEP
ENTRY(Java_java_util_ResourceBundle_getClassContext) ENTRY_SEP
ENTRY(Java_java_lang_Runtime_freeMemory) ENTRY_SEP
ENTRY(Java_java_lang_Runtime_gc) ENTRY_SEP
ENTRY(Java_java_lang_Runtime_maxMemory) ENTRY_SEP
ENTRY(Java_java_lang_Runtime_runFinalization0) ENTRY_SEP
ENTRY(Java_java_lang_Runtime_safeExit) ENTRY_SEP
ENTRY(Java_java_lang_Runtime_totalMemory) ENTRY_SEP
ENTRY(Java_java_lang_Runtime_traceInstructions) ENTRY_SEP
ENTRY(Java_java_lang_Runtime_traceMethodCalls) ENTRY_SEP
ENTRY(Java_java_lang_Runtime_execInternal) ENTRY_SEP
ENTRY(Java_java_lang_SecurityManager_getClassContext) ENTRY_SEP
ENTRY(Java_java_lang_Shutdown_halt) ENTRY_SEP
ENTRY(Java_java_lang_Shutdown_runAllFinalizers) ENTRY_SEP
ENTRY(Java_java_lang_StrictMath_IEEEremainder) ENTRY_SEP
ENTRY(Java_java_lang_StrictMath_acos) ENTRY_SEP
ENTRY(Java_java_lang_StrictMath_asin) ENTRY_SEP
ENTRY(Java_java_lang_StrictMath_atan2) ENTRY_SEP
ENTRY(Java_java_lang_StrictMath_ceil) ENTRY_SEP
ENTRY(Java_java_lang_StrictMath_cos) ENTRY_SEP
ENTRY(Java_java_lang_StrictMath_exp) ENTRY_SEP
ENTRY(Java_java_lang_StrictMath_floor) ENTRY_SEP
ENTRY(Java_java_lang_StrictMath_log) ENTRY_SEP
ENTRY(Java_java_lang_StrictMath_pow) ENTRY_SEP
ENTRY(Java_java_lang_StrictMath_rint) ENTRY_SEP
ENTRY(Java_java_lang_StrictMath_sin) ENTRY_SEP
ENTRY(Java_java_lang_StrictMath_sqrt) ENTRY_SEP
ENTRY(Java_java_lang_StrictMath_tan) ENTRY_SEP
ENTRY(Java_java_io_SymbianFileSystem_canonicalize0) ENTRY_SEP
ENTRY(Java_java_io_SymbianFileSystem_checkAccess) ENTRY_SEP
ENTRY(Java_java_io_SymbianFileSystem_createDirectory) ENTRY_SEP
ENTRY(Java_java_io_SymbianFileSystem_createFileExclusively) ENTRY_SEP
ENTRY(Java_java_io_SymbianFileSystem_delete0) ENTRY_SEP
ENTRY(Java_java_io_SymbianFileSystem_deleteOnExit) ENTRY_SEP
ENTRY(Java_java_io_SymbianFileSystem_getBooleanAttributes) ENTRY_SEP
ENTRY(Java_java_io_SymbianFileSystem_getDriveDirectory) ENTRY_SEP
ENTRY(Java_java_io_SymbianFileSystem_getLastModifiedTime) ENTRY_SEP
ENTRY(Java_java_io_SymbianFileSystem_getLength) ENTRY_SEP
ENTRY(Java_java_io_SymbianFileSystem_initIDs) ENTRY_SEP
ENTRY(Java_java_io_SymbianFileSystem_list) ENTRY_SEP
ENTRY(Java_java_io_SymbianFileSystem_rename0) ENTRY_SEP
ENTRY(Java_java_io_SymbianFileSystem_setLastModifiedTime) ENTRY_SEP
ENTRY(Java_java_io_SymbianFileSystem_setReadOnly) ENTRY_SEP
ENTRY(Java_java_lang_System_getCallerClass) ENTRY_SEP
ENTRY(Java_java_lang_System_identityHashCode) ENTRY_SEP
ENTRY(Java_java_lang_System_initCldcMidpProperties) ENTRY_SEP
ENTRY(Java_java_lang_System_initProperties) ENTRY_SEP
ENTRY(Java_java_lang_System_mapLibraryName) ENTRY_SEP
ENTRY(Java_java_lang_System_setErr0) ENTRY_SEP
ENTRY(Java_java_lang_System_setIn0) ENTRY_SEP
ENTRY(Java_java_lang_System_setOut0) ENTRY_SEP
ENTRY(Java_java_lang_Thread_setCurrentThread) ENTRY_SEP
ENTRY(Java_java_lang_Thread_setThreadExiting) ENTRY_SEP
ENTRY(Java_java_lang_Throwable_fillInStackTrace) ENTRY_SEP
ENTRY(Java_java_lang_Throwable_getStackTraceDepth) ENTRY_SEP
ENTRY(Java_java_lang_Throwable_getStackTraceElement) ENTRY_SEP
ENTRY(Java_java_util_TimeZone_getSystemGMTOffsetID) ENTRY_SEP
ENTRY(Java_java_util_TimeZone_getSystemTimeZoneID) ENTRY_SEP
ENTRY(Java_java_util_zip_ZipEntry_initFields) ENTRY_SEP
ENTRY(Java_java_util_zip_ZipEntry_initIDs) ENTRY_SEP
ENTRY(Java_java_util_jar_JarFile_getMetaInfEntryNames) ENTRY_SEP
ENTRY(Java_java_util_zip_ZipFile_close) ENTRY_SEP
ENTRY(Java_java_util_zip_ZipFile_freeEntry) ENTRY_SEP
ENTRY(Java_java_util_zip_ZipFile_getCSize) ENTRY_SEP
ENTRY(Java_java_util_zip_ZipFile_getEntry) ENTRY_SEP
ENTRY(Java_java_util_zip_ZipFile_getMethod) ENTRY_SEP
ENTRY(Java_java_util_zip_ZipFile_getNextEntry) ENTRY_SEP
ENTRY(Java_java_util_zip_ZipFile_getSize) ENTRY_SEP
ENTRY(Java_java_util_zip_ZipFile_getTotal) ENTRY_SEP
ENTRY(Java_java_util_zip_ZipFile_getZipMessage) ENTRY_SEP
ENTRY(Java_java_util_zip_ZipFile_initIDs) ENTRY_SEP
ENTRY(Java_java_util_zip_ZipFile_open) ENTRY_SEP
ENTRY(Java_java_util_zip_ZipFile_read) ENTRY_SEP
ENTRY(Java_java_lang_Class_getSuperclass) ENTRY_SEP
ENTRY(Java_java_lang_ClassLoader_retrieveDirectives) ENTRY_SEP
ENTRY(Java_java_lang_Class_desiredAssertionStatus0) ENTRY_SEP
ENTRY(Java_java_lang_Class_getClassLoader0) ENTRY_SEP
ENTRY(Java_java_lang_Class_getComponentType) ENTRY_SEP
ENTRY(Java_java_lang_Class_getConstructor0) ENTRY_SEP
ENTRY(Java_java_lang_Class_getConstructors0) ENTRY_SEP
ENTRY(Java_java_lang_Class_getDeclaredClasses0) ENTRY_SEP
ENTRY(Java_java_lang_Class_getDeclaringClass) ENTRY_SEP
ENTRY(Java_java_lang_Class_getField0) ENTRY_SEP
ENTRY(Java_java_lang_Class_getFields0) ENTRY_SEP
ENTRY(Java_java_lang_Class_getInterfaces) ENTRY_SEP
ENTRY(Java_java_lang_Class_getMethod0) ENTRY_SEP
ENTRY(Java_java_lang_Class_getMethods0) ENTRY_SEP
ENTRY(Java_java_lang_Class_getModifiers) ENTRY_SEP
ENTRY(Java_java_lang_Class_getName) ENTRY_SEP
ENTRY(Java_java_lang_Class_getProtectionDomain0) ENTRY_SEP
ENTRY(Java_java_lang_Class_isArray) ENTRY_SEP
ENTRY(Java_java_lang_Class_isPrimitive) ENTRY_SEP
ENTRY(Java_java_lang_Compiler_command) ENTRY_SEP
ENTRY(Java_java_lang_Compiler_compileClass) ENTRY_SEP
ENTRY(Java_java_lang_Compiler_compileClasses) ENTRY_SEP
ENTRY(Java_java_lang_Compiler_disable) ENTRY_SEP
ENTRY(Java_java_lang_Compiler_enable) ENTRY_SEP
ENTRY(Java_java_lang_Compiler_initialize) ENTRY_SEP
ENTRY(Java_java_lang_System_arraycopy) ENTRY_SEP
ENTRY(Java_java_lang_System_currentTimeMillis) ENTRY_SEP
ENTRY(Java_java_lang_Thread_currentThread) ENTRY_SEP
ENTRY(Java_java_lang_Thread_holdsLock) ENTRY_SEP
ENTRY(Java_java_lang_Thread_interrupt0) ENTRY_SEP
ENTRY(Java_java_lang_Thread_isInterrupted) ENTRY_SEP
ENTRY(Java_java_lang_Thread_runNative) ENTRY_SEP
ENTRY(Java_java_lang_Thread_setPriority0) ENTRY_SEP
ENTRY(Java_java_lang_Thread_sleep0) ENTRY_SEP
ENTRY(Java_java_lang_Thread_start0) ENTRY_SEP
ENTRY(Java_java_lang_Thread_yield) ENTRY_SEP
ENTRY(Java_java_util_zip_CRC32_updateBytes)

